name: LAPIS-SILO E2E Tests
on:
  push:
  schedule:
    - cron: '0/5 * * * *'


jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: prepare pnpm
              run: npm i -g pnpm
            - name: pnpm i
              run: pnpm i
            - name: test
              id: test
#                pnpm test | tee test_output.txt
              run: |
                  npm run fail | tee test_output.txt
                  test ${PIPESTATUS[0]} -eq 0

#              run: |
#                  npm run fail > test_output.txt
#                  exit_code=$?
#                  echo "test-output<<EOF" >> $GITHUB_OUTPUT
#                  cat test_output.txt >> $GITHUB_OUTPUT
#                  echo "EOF" >> $GITHUB_OUTPUT
#                  exit $exit_code
#              env:
#                  LAPIS_TAG: latest
#                  SILO_TAG: latest

            - name: Retrieve test results
              id: test-results2
              run: |
                  echo "test-output2=asdlfkjasdf" >> $GITHUB_OUTPUT

            - name: Only on schedule
              if: github.event_name == 'schedule'
              run: echo "This job was triggered by a schedule event."

            - name: output event
              if: always()
              run: |
                  ${{ toJson(github.event) }}

            - name: output schedule event
              if: always()
              run: |
                  ${{ toJson(github.event.schedule) }}

            - name: Retrieve test results
              if: failure()
              id: test-results
              run: |
                  echo "test-output<<EOF" >> $GITHUB_OUTPUT
                  cat test_output.txt >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Notify failed build
              uses: jayqi/failed-build-issue-action@v1
              if: failure()
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  title-template: My title
                  body-template: |
                      Tests failed!
                    
                      Ref: ${{ github.ref }}
                      Sha: ${{ github.sha }}
                      Run number ${{ github.run_number }}, attempt ${{ github.run_attempt }}
                    
                      ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}
                      
                      <details>
                      <summary>Expand to see test output</summary>
                      ${{ steps.test-results.outputs.test-output }}
                      </details>

#    check-format:
#        name: Check format
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v4
#            - uses: actions/setup-node@v4
#              with:
#                  node-version-file: '.nvmrc'
#            - uses: actions/cache@v4
#              with:
#                  path: ~/.npm
#                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
#            - run: npm ci
#            - run: npm run check-format
#
#    check-types:
#        name: Check types
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v4
#            - uses: actions/setup-node@v4
#              with:
#                  node-version-file: '.nvmrc'
#            - uses: actions/cache@v4
#              with:
#                  path: ~/.npm
#                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
#            - run: npm ci
#            - run: npm run check-types
